### Lista customers
GET http://localhost:3000/customers

### Agregar customer
POST http://localhost:3000/customers
content-type: application/json

{
  "code": "123456",
  "name": "Prueba",
  "active": true
}

### Actualizar customer || Se pasa el id del registro a modificar en la url
PUT http://localhost:3000/customers/1
content-type: application/json

{
  "name": "Bebidas gaseosas",
  "code": "234567",
  "active": false
}

### Obtener customer pasando el id || Se pasa el id del registro a modificar en la url
GET http://localhost:3000/customers/1
content-type: application/json

### Eliminar customer pasando el id || Se pasa el id del registro a eliminar en la url
DELETE http://localhost:3000/customers/1
content-type: application/json

### Eliminar todos los customers // No se pasa ningún id
DELETE http://localhost:3000/customers
content-type: application/json